---
- name: Install packages on local Ubuntu
  hosts: localhost
  become: yes
  connection: local

  vars:
    packages:
      - git
      - curl
      - vim
      - htop
      - wireshark
      - tshark
      - virt-manager
      - vlc
      - unzip
      - unrar
      - tcpdump
      - strace
      - sshfs
      - rsync
      - gparted
      - mc
      - lsof
      - jq
      - hashcat
      - gnupg
      - gimp
      - fuse3
      - ffmpeg
      - yt-dlp
      - eog
      - autofs
      - keyd

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name: "{{ packages }}"
        state: present
